const countries = [
    { name: 'Afghanistan', code: 'AF', dial: '+93' },
    { name: 'Albania', code: 'AL', dial: '+355' },
    { name: 'Algeria', code: 'DZ', dial: '+213' },
    { name: 'Andorra', code: 'AD', dial: '+376' },
    { name: 'Angola', code: 'AO', dial: '+244' },
    { name: 'Argentina', code: 'AR', dial: '+54' },
    { name: 'Armenia', code: 'AM', dial: '+374' },
    { name: 'Australia', code: 'AU', dial: '+61' },
    { name: 'Austria', code: 'AT', dial: '+43' },
    { name: 'Azerbaijan', code: 'AZ', dial: '+994' },
    { name: 'Bahrain', code: 'BH', dial: '+973' },
    { name: 'Bangladesh', code: 'BD', dial: '+880' },
    { name: 'Belarus', code: 'BY', dial: '+375' },
    { name: 'Belgium', code: 'BE', dial: '+32' },
    { name: 'Bolivia', code: 'BO', dial: '+591' },
    { name: 'Bosnia', code: 'BA', dial: '+387' },
    { name: 'Brazil', code: 'BR', dial: '+55' },
    { name: 'Bulgaria', code: 'BG', dial: '+359' },
    { name: 'Cambodia', code: 'KH', dial: '+855' },
    { name: 'Cameroon', code: 'CM', dial: '+237' },
    { name: 'Canada', code: 'CA', dial: '+1' },
    { name: 'Chile', code: 'CL', dial: '+56' },
    { name: 'China', code: 'CN', dial: '+86' },
    { name: 'Colombia', code: 'CO', dial: '+57' },
    { name: 'Congo', code: 'CG', dial: '+242' },
    { name: 'Costa Rica', code: 'CR', dial: '+506' },
    { name: 'Croatia', code: 'HR', dial: '+385' },
    { name: 'Cuba', code: 'CU', dial: '+53' },
    { name: 'Cyprus', code: 'CY', dial: '+357' },
    { name: 'Czech Republic', code: 'CZ', dial: '+420' },
    { name: 'Denmark', code: 'DK', dial: '+45' },
    { name: 'Ecuador', code: 'EC', dial: '+593' },
    { name: 'Egypt', code: 'EG', dial: '+20' },
    { name: 'Estonia', code: 'EE', dial: '+372' },
    { name: 'Ethiopia', code: 'ET', dial: '+251' },
    { name: 'Finland', code: 'FI', dial: '+358' },
    { name: 'France', code: 'FR', dial: '+33' },
    { name: 'Georgia', code: 'GE', dial: '+995' },
    { name: 'Germany', code: 'DE', dial: '+49' },
    { name: 'Ghana', code: 'GH', dial: '+233' },
    { name: 'Greece', code: 'GR', dial: '+30' },
    { name: 'Guatemala', code: 'GT', dial: '+502' },
    { name: 'Honduras', code: 'HN', dial: '+504' },
    { name: 'Hong Kong', code: 'HK', dial: '+852' },
    { name: 'Hungary', code: 'HU', dial: '+36' },
    { name: 'Iceland', code: 'IS', dial: '+354' },
    { name: 'India', code: 'IN', dial: '+91' },
    { name: 'Indonesia', code: 'ID', dial: '+62' },
    { name: 'Iran', code: 'IR', dial: '+98' },
    { name: 'Iraq', code: 'IQ', dial: '+964' },
    { name: 'Ireland', code: 'IE', dial: '+353' },
    { name: 'Israel', code: 'IL', dial: '+972' },
    { name: 'Italy', code: 'IT', dial: '+39' },
    { name: 'Jamaica', code: 'JM', dial: '+1876' },
    { name: 'Japan', code: 'JP', dial: '+81' },
    { name: 'Jordan', code: 'JO', dial: '+962' },
    { name: 'Kazakhstan', code: 'KZ', dial: '+7' },
    { name: 'Kenya', code: 'KE', dial: '+254' },
    { name: 'Kuwait', code: 'KW', dial: '+965' },
    { name: 'Kyrgyzstan', code: 'KG', dial: '+996' },
    { name: 'Latvia', code: 'LV', dial: '+371' },
    { name: 'Lebanon', code: 'LB', dial: '+961' },
    { name: 'Libya', code: 'LY', dial: '+218' },
    { name: 'Lithuania', code: 'LT', dial: '+370' },
    { name: 'Luxembourg', code: 'LU', dial: '+352' },
    { name: 'Malaysia', code: 'MY', dial: '+60' },
    { name: 'Maldives', code: 'MV', dial: '+960' },
    { name: 'Mexico', code: 'MX', dial: '+52' },
    { name: 'Moldova', code: 'MD', dial: '+373' },
    { name: 'Mongolia', code: 'MN', dial: '+976' },
    { name: 'Morocco', code: 'MA', dial: '+212' },
    { name: 'Mozambique', code: 'MZ', dial: '+258' },
    { name: 'Myanmar', code: 'MM', dial: '+95' },
    { name: 'Nepal', code: 'NP', dial: '+977' },
    { name: 'Netherlands', code: 'NL', dial: '+31' },
    { name: 'New Zealand', code: 'NZ', dial: '+64' },
    { name: 'Nigeria', code: 'NG', dial: '+234' },
    { name: 'Norway', code: 'NO', dial: '+47' },
    { name: 'Oman', code: 'OM', dial: '+968' },
    { name: 'Pakistan', code: 'PK', dial: '+92' },
    { name: 'Palestine', code: 'PS', dial: '+970' },
    { name: 'Panama', code: 'PA', dial: '+507' },
    { name: 'Paraguay', code: 'PY', dial: '+595' },
    { name: 'Peru', code: 'PE', dial: '+51' },
    { name: 'Philippines', code: 'PH', dial: '+63' },
    { name: 'Poland', code: 'PL', dial: '+48' },
    { name: 'Portugal', code: 'PT', dial: '+351' },
    { name: 'Qatar', code: 'QA', dial: '+974' },
    { name: 'Romania', code: 'RO', dial: '+40' },
    { name: 'Russia', code: 'RU', dial: '+7' },
    { name: 'Rwanda', code: 'RW', dial: '+250' },
    { name: 'Saudi Arabia', code: 'SA', dial: '+966' },
    { name: 'Senegal', code: 'SN', dial: '+221' },
    { name: 'Serbia', code: 'RS', dial: '+381' },
    { name: 'Singapore', code: 'SG', dial: '+65' },
    { name: 'Slovakia', code: 'SK', dial: '+421' },
    { name: 'Slovenia', code: 'SI', dial: '+386' },
    { name: 'Somalia', code: 'SO', dial: '+252' },
    { name: 'South Africa', code: 'ZA', dial: '+27' },
    { name: 'South Korea', code: 'KR', dial: '+82' },
    { name: 'Spain', code: 'ES', dial: '+34' },
    { name: 'Sri Lanka', code: 'LK', dial: '+94' },
    { name: 'Sudan', code: 'SD', dial: '+249' },
    { name: 'Sweden', code: 'SE', dial: '+46' },
    { name: 'Switzerland', code: 'CH', dial: '+41' },
    { name: 'Syria', code: 'SY', dial: '+963' },
    { name: 'Taiwan', code: 'TW', dial: '+886' },
    { name: 'Tajikistan', code: 'TJ', dial: '+992' },
    { name: 'Tanzania', code: 'TZ', dial: '+255' },
    { name: 'Thailand', code: 'TH', dial: '+66' },
    { name: 'Tunisia', code: 'TN', dial: '+216' },
    { name: 'Turkey', code: 'TR', dial: '+90' },
    { name: 'Turkmenistan', code: 'TM', dial: '+993' },
    { name: 'UAE', code: 'AE', dial: '+971' },
    { name: 'Uganda', code: 'UG', dial: '+256' },
    { name: 'Ukraine', code: 'UA', dial: '+380' },
    { name: 'United Kingdom', code: 'GB', dial: '+44' },
    { name: 'United States', code: 'US', dial: '+1' },
    { name: 'Uruguay', code: 'UY', dial: '+598' },
    { name: 'Uzbekistan', code: 'UZ', dial: '+998' },
    { name: 'Venezuela', code: 'VE', dial: '+58' },
    { name: 'Vietnam', code: 'VN', dial: '+84' },
    { name: 'Yemen', code: 'YE', dial: '+967' },
    { name: 'Zimbabwe', code: 'ZW', dial: '+263' },
];

export default countries;